USE db1901321057

CREATE TABLE Countries
(
COUNTRY_CODE char(3) NOT NULL,
NAME nvarchar(40) NOT NULL,
POPULATION int NOT NULL
)

ALTER TABLE Countries ADD PHONE_CODE int NOT NULL

INSERT INTO Countries (COUNTRY_CODE,NAME,POPULATION,PHONE_CODE)
VALUES ('ENG',N'Англия',600000,089)

INSERT INTO Countries (COUNTRY_CODE,NAME,POPULATION,PHONE_CODE)
VALUES ('BGR',N'БЪЛГАРИЯ',75000000,359)

SELECT * FROM Countries WHERE PHONE_CODE = 089

SELECT * FROM Countries
SELECT NAME,PHONE_CODE FROM Countries

